"""backtest_time_metrics

Revision ID: 1dba12fd5771
Revises: e540958e82ae
Create Date: 2025-10-24 11:32:07.358962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1dba12fd5771'
down_revision: Union[str, None] = 'e540958e82ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_tasks', sa.Column('times_metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_tasks', 'times_metrics')
    # ### end Alembic commands ###
