"""risk_logs

Revision ID: 49ba2e5fe232
Revises: 8f7a4518b104
Create Date: 2025-08-29 10:43:11.602420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ba2e5fe232'
down_revision: Union[str, None] = '8f7a4518b104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_logs',
    sa.Column('project_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='项目ID'),
    sa.Column('risk_type', sa.String(length=32), nullable=False, comment='风控类型: embedded/signal/active'),
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='策略ID'),
    sa.Column('strategy_instance_id', sa.String(length=200), nullable=True, comment='策略实例ID'),
    sa.Column('strategy_class_name', sa.String(length=200), nullable=True, comment='策略类名'),
    sa.Column('risk_policy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='风控策略实例ID'),
    sa.Column('risk_policy_class_name', sa.String(length=200), nullable=False, comment='风控策略类名'),
    sa.Column('trigger_time', sa.DateTime(), nullable=False, comment='触发时间'),
    sa.Column('trigger_reason', sa.Text(), nullable=True, comment='触发原因描述'),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='信号ID'),
    sa.Column('execution_order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='执行订单ID'),
    sa.Column('position_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='仓位ID'),
    sa.Column('original_amount', sa.DECIMAL(precision=36, scale=20), nullable=True, comment='原始交易金额'),
    sa.Column('pnl', sa.DECIMAL(precision=36, scale=20), nullable=True, comment='盈亏金额'),
    sa.Column('extra_info', sa.JSON(), nullable=True, comment='额外信息'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_log_project_time', 'risk_logs', ['project_id', 'trigger_time'], unique=False)
    op.create_index('idx_risk_log_strategy_time', 'risk_logs', ['strategy_instance_id', 'trigger_time'], unique=False)
    op.create_index('idx_risk_log_type_time', 'risk_logs', ['risk_type', 'trigger_time'], unique=False)
    op.create_index(op.f('ix_risk_logs_created_at'), 'risk_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_logs_execution_order_id'), 'risk_logs', ['execution_order_id'], unique=False)
    op.create_index(op.f('ix_risk_logs_id'), 'risk_logs', ['id'], unique=False)
    op.create_index(op.f('ix_risk_logs_position_id'), 'risk_logs', ['position_id'], unique=False)
    op.create_index(op.f('ix_risk_logs_project_id'), 'risk_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_risk_logs_risk_type'), 'risk_logs', ['risk_type'], unique=False)
    op.create_index(op.f('ix_risk_logs_signal_id'), 'risk_logs', ['signal_id'], unique=False)
    op.create_index(op.f('ix_risk_logs_strategy_id'), 'risk_logs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_risk_logs_strategy_instance_id'), 'risk_logs', ['strategy_instance_id'], unique=False)
    op.create_index(op.f('ix_risk_logs_trigger_time'), 'risk_logs', ['trigger_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_logs_trigger_time'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_strategy_instance_id'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_strategy_id'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_signal_id'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_risk_type'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_project_id'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_position_id'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_id'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_execution_order_id'), table_name='risk_logs')
    op.drop_index(op.f('ix_risk_logs_created_at'), table_name='risk_logs')
    op.drop_index('idx_risk_log_type_time', table_name='risk_logs')
    op.drop_index('idx_risk_log_strategy_time', table_name='risk_logs')
    op.drop_index('idx_risk_log_project_time', table_name='risk_logs')
    op.drop_table('risk_logs')
    # ### end Alembic commands ###
