"""factor

Revision ID: 4f6cb11c7770
Revises: 1dba12fd5771
Create Date: 2025-11-25 16:19:09.153638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4f6cb11c7770'
down_revision: Union[str, None] = '1dba12fd5771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factors',
    sa.Column('factor_count', sa.Integer(), nullable=False, comment='因子数量'),
    sa.Column('output_names', sa.JSON(), nullable=True, comment='输出名称列表'),
    sa.Column('categories', sa.JSON(), nullable=True, comment='因子分类列表'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('class_name', sa.String(length=200), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factors_id'), 'factors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factors_id'), table_name='factors')
    op.drop_table('factors')
    # ### end Alembic commands ###
