"""value_performence

Revision ID: 6189d0fea6a4
Revises: b2a313dfd7fb
Create Date: 2025-09-15 17:30:29.784935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6189d0fea6a4'
down_revision: Union[str, None] = 'b2a313dfd7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_snapshots', sa.Column('principal', sa.Numeric(precision=36, scale=18), nullable=True, comment='本金'))
    op.drop_column('strategies', 'exit_strategy_config')
    op.drop_column('strategies', 'enter_strategy_config')
    op.drop_column('strategies', 'enter_strategy_class_name')
    op.drop_column('strategies', 'exit_strategy_class_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('exit_strategy_class_name', sa.VARCHAR(length=200), nullable=False))
    op.add_column('strategies', sa.Column('enter_strategy_class_name', sa.VARCHAR(length=200), nullable=False))
    op.add_column('strategies', sa.Column('enter_strategy_config', sqlite.JSON(), nullable=True))
    op.add_column('strategies', sa.Column('exit_strategy_config', sqlite.JSON(), nullable=True))
    op.drop_column('asset_snapshots', 'principal')
    # ### end Alembic commands ###
