"""risk_policy

Revision ID: 8f7a4518b104
Revises: 35b47490ebe3
Create Date: 2025-08-26 16:17:19.315607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7a4518b104'
down_revision: Union[str, None] = '35b47490ebe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_policies',
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('strategy_template_ids', sa.JSON(), nullable=True),
    sa.Column('strategy_instance_ids', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('class_name', sa.String(length=200), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_policies_created_at'), 'risk_policies', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_policies_id'), 'risk_policies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_policies_id'), table_name='risk_policies')
    op.drop_index(op.f('ix_risk_policies_created_at'), table_name='risk_policies')
    op.drop_table('risk_policies')
    # ### end Alembic commands ###
