"""add asset snapshots table

Revision ID: add_asset_snapshots
Revises: 2b28e0bc0951
Create Date: 2025-07-28 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_asset_snapshots'
down_revision: Union[str, None] = '2b28e0bc0951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_snapshots',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False, comment='快照时间'),
    sa.Column('activate_amount', sa.DECIMAL(precision=36, scale=18), nullable=False, comment='激活金额'),
    sa.Column('pnl', sa.DECIMAL(precision=36, scale=18), nullable=False, comment='盈亏'),
    sa.Column('friction', sa.DECIMAL(precision=36, scale=18), nullable=False, comment='摩擦成本'),
    sa.Column('fee', sa.DECIMAL(precision=36, scale=18), nullable=False, comment='手续费'),
    sa.Column('total_amount', sa.DECIMAL(precision=36, scale=18), nullable=False, comment='总金额'),
    sa.Column('virtual_pnl', sa.DECIMAL(precision=36, scale=18), nullable=False, comment='虚拟盈亏'),
    sa.Column('position_amount', sa.Integer(), nullable=False, comment='仓位数量'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_snapshots_id'), 'asset_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_asset_snapshots_project_id'), 'asset_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_asset_snapshots_snapshot_time'), 'asset_snapshots', ['snapshot_time'], unique=False)
    op.create_index('idx_project_snapshot_time', 'asset_snapshots', ['project_id', 'snapshot_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_snapshot_time', table_name='asset_snapshots')
    op.drop_index(op.f('ix_asset_snapshots_snapshot_time'), table_name='asset_snapshots')
    op.drop_index(op.f('ix_asset_snapshots_project_id'), table_name='asset_snapshots')
    op.drop_index(op.f('ix_asset_snapshots_id'), table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    # ### end Alembic commands ### 