"""virtual_pos

Revision ID: b2a313dfd7fb
Revises: 49ba2e5fe232
Create Date: 2025-08-29 18:12:25.089473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a313dfd7fb'
down_revision: Union[str, None] = '49ba2e5fe232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('virtual_positions', sa.JSON(), nullable=True, comment='虚拟仓位列表'))
    op.drop_column('positions', 'is_fake')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('is_fake', sa.BOOLEAN(), nullable=True))
    op.drop_column('positions', 'virtual_positions')
    # ### end Alembic commands ###
