"""add_long_short_win_rate

Revision ID: e540958e82ae
Revises: 5da9140e0252
Create Date: 2025-10-09 19:45:29.960047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e540958e82ae'
down_revision: Union[str, None] = '6189d0fea6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_tasks', sa.Column('long_win_rate', sa.Float(), nullable=True))
    op.add_column('backtest_tasks', sa.Column('short_win_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_tasks', 'short_win_rate')
    op.drop_column('backtest_tasks', 'long_win_rate')
    # ### end Alembic commands ###
