"""ml

Revision ID: f4cee0271a9c
Revises: c376c84d11f1
Create Date: 2025-12-02 10:28:51.340636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f4cee0271a9c'
down_revision: Union[str, None] = 'c376c84d11f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_generators',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('class_name', sa.String(length=200), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_generators_id'), 'label_generators', ['id'], unique=False)
    op.create_table('model_training_tasks',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True, comment='Request configuration snapshot'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending | running | completed | failed'),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('data_config_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=32), nullable=True),
    sa.Column('end_time', sa.String(length=32), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('timeframes', sa.JSON(), nullable=True),
    sa.Column('factor_ids', sa.JSON(), nullable=True, comment='List of factor IDs'),
    sa.Column('label_generator_id', sa.Integer(), nullable=True, comment='FK to label_generators'),
    sa.Column('trainer_id', sa.Integer(), nullable=True, comment='FK to trainers'),
    sa.Column('train_split_ratio', sa.Float(), nullable=False, comment='Training data ratio (0.01-0.99)'),
    sa.Column('metrics', sa.JSON(), nullable=True, comment='Training and validation metrics'),
    sa.Column('model_id', sa.Integer(), nullable=True, comment='FK to models (created after successful training)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_training_tasks_id'), 'model_training_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_model_training_tasks_project_id'), 'model_training_tasks', ['project_id'], unique=False)
    op.create_table('models',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Relative path to model file'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='File size in bytes'),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_project_id'), 'models', ['project_id'], unique=False)
    op.create_table('trainers',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('class_name', sa.String(length=200), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainers_id'), 'trainers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainers_id'), table_name='trainers')
    op.drop_table('trainers')
    op.drop_index(op.f('ix_models_project_id'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_model_training_tasks_project_id'), table_name='model_training_tasks')
    op.drop_index(op.f('ix_model_training_tasks_id'), table_name='model_training_tasks')
    op.drop_table('model_training_tasks')
    op.drop_index(op.f('ix_label_generators_id'), table_name='label_generators')
    op.drop_table('label_generators')
    # ### end Alembic commands ###
